name: .NET Core API CI/CD to Azure

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal

      - name: Publish API Project
        run: dotnet publish WebAPI/WebAPI.csproj --configuration Release --output ./publish_output
        # This will publish only the necessary files to the ./publish_output folder

      - name: Upload publish_output as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: publish-output
          path: ./publish_output

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download publish_output artifact
        uses: actions/download-artifact@v3
        with:
          name: publish-output

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "DotNetCoreAzureGitHubApp"
          slot-name: "production"
          package: ./publish_output  # Deploys only the Web API publish output
